[build]
  publish = "public"
  functions = "api"
  command = "npm install"

[[redirects]]
  from = "/demographic-builder"
  to = "/demographic-builder.html"
  status = 200

[[redirects]]
  from = "/intake"
  to = "/intake-form.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
